# Generated by Django 4.0.1 on 2022-03-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('team', models.CharField(max_length=70)),
                ('price', models.CharField(max_length=70)),
                ('play', models.CharField(max_length=70)),
                ('role', models.CharField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
